language: java
# skip installation step
install: true
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
cache:
  directories:
  - $HOME/.m2
script:
- mvn -f pom.xml clean verify -Pjacoco coveralls:report