language: java
# skip installation step
install: true
sudo: false

cache:
  directories:
  - $HOME/.m2

matrix:
    fast_finish: true

  - jdk: oraclejdk8
    env: WITH_COVERALLS=true

  - jdk: oraclejdk7

  - jdk: openjdk6

script:
 - if [ "$WITH_COVERALLS" == "true" ];
   then mvn -f /pom.xml clean verify -Pjacoco coveralls:report;
   else mvn -f /pom.xml clean verify;
   fi