language: java

install: true

sudo: false

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
          env: WITH_COVERALLS=true
        - jdk: oraclejdk7
        - jdk: openjdk6
        - os: osx
          osx_image: xcode8

cache:
  directories:
  - $HOME/.m2


script:
 - if [ "$WITH_COVERALLS" == "true" ];
   then mvn -f pom.xml clean verify -Pjacoco coveralls:report;
   else mvn -f pom.xml clean verify;
   fi